# Generated by Django 3.1.9 on 2021-08-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='annual_interest_rate',
        ),
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='interest_calculation_per_year',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='interest_start_date',
        ),
    ]
