# Generated by Django 3.1.9 on 2021-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
