# Generated by Django 3.1.9 on 2021-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
