# Generated by Django 3.1.9 on 2021-08-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210816_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
