# Generated by Django 3.1.9 on 2021-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_account2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account2',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
