# Generated by Django 3.1.9 on 2021-08-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
